
#include <ProcessingUnit/A64InstructionSet/A64InstructionSet.h>

BEGIN_NAMESPACE

IMPLEMENT_AS_SINGLETON(BranchExceptionSystemGroup)
IMPLEMENT_AS_SINGLETON(DataProcessingImmediateGroup)
IMPLEMENT_AS_SINGLETON(DataProcessingRegisterGroup)
IMPLEMENT_AS_SINGLETON(DataProcessingScalarFloatingPointAdvancedSIMDGroup)
IMPLEMENT_AS_SINGLETON(LoadStoreGroup)
IMPLEMENT_AS_SINGLETON(ReservedGroup)

END_NAMESPACE
